// This code was generated by a cloud-generators-net tool
// (see https://github.com/Kentico/cloud-generators-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.

using System.Collections.Generic;

using KenticoCloud.Delivery;

namespace VERSUS.Kentico.Models
{
    public partial class SiteSection
    {
        public const string Codename = "site_section";
        public const string IconCodename = "icon";
        public const string DescriptionCodename = "description";
        public const string TitleCodename = "title";

        public IEnumerable<Asset> Icon { get; set; }

        public IRichTextContent Description { get; set; }

        public string Title { get; set; }

        public ContentItemSystemAttributes System { get; set; }
    }
}