// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace VERSUS.Kentico.Models
{
    public partial class SiteLogo
    {
        public const string Codename = "site_logo";
        public const string LogoCodename = "logo";

        public IEnumerable<Asset> Logo { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}