// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace VERSUS.Kentico.Types
{
    public partial class Announcement
    {
        public const string Codename = "announcement";
        public const string LevelCodename = "level";
        public const string LocationCodename = "location";
        public const string BodyCodename = "body";
        public const string TitleCodename = "title";

        public IEnumerable<MultipleChoiceOption> Level { get; set; }
        public IEnumerable<MultipleChoiceOption> Location { get; set; }
        public IRichTextContent Body { get; set; }
        public string Title { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}