// This code was generated by a cloud-generators-net tool
// (see https://github.com/Kentico/cloud-generators-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;

using KenticoCloud.Delivery;

namespace VERSUS.Kentico.Types
{
    public partial class Shirt
    {
        public const string Codename = "shirt";
        public const string ListableMainImagesCodename = "listable__main_images";
        public const string ListableDescriptionCodename = "listable__description";
        public const string ListableReleaseDateCodename = "listable__release_date";
        public const string WearableSizeCodename = "wearable__size";
        public const string ColorsCodename = "colors";
        public const string ListablePriceCodename = "listable__price";
        public const string WearableGenderCodename = "wearable__gender";

        public IEnumerable<Asset> ListableMainImages { get; set; }

        public IRichTextContent ListableDescription { get; set; }

        public DateTime? ListableReleaseDate { get; set; }

        public decimal? WearableSize { get; set; }

        public IEnumerable<MultipleChoiceOption> Colors { get; set; }

        public decimal? ListablePrice { get; set; }

        public IEnumerable<MultipleChoiceOption> WearableGender { get; set; }

        public ContentItemSystemAttributes System { get; set; }
    }
}