// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace VERSUS.Kentico.Types
{
    public partial class SidebarItem
    {
        public const string Codename = "sidebar_item";
        public const string LocationCodename = "location";
        public const string TypeCodename = "type";
        public const string IconCodename = "icon";
        public const string TitleCodename = "title";
        public const string DestinationCodename = "destination";

        public IEnumerable<MultipleChoiceOption> Location { get; set; }
        public IEnumerable<MultipleChoiceOption> Type { get; set; }
        public IEnumerable<Asset> Icon { get; set; }
        public string Title { get; set; }
        public IEnumerable<object> Destination { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}